config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
match '/time_entries/:id/show', :to => 'timelog#show',  :as => :show_time_entries,  :via => :get, :id => /\d+/

app/views/timelog/_list.html.erb
<%= form_tag({}, :data => {:cm_url => time_entries_context_menu_path}) do -%>
<%= hidden_field_tag 'back_url', url_for(:params => request.query_parameters), :id => nil %>
<div class="autoscroll">
<table class="list odd-even time-entries">
<thead>
  <tr>
    <th class="checkbox hide-when-print">
      <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
        :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
    </th>
    <% @query.inline_columns.each do |column| %>
      <%= column_header(@query, column) %>
    <% end %>
    <th></th>
  </tr>
</thead>
<tbody>
<% grouped_query_results(entries, @query) do |entry, group_name, group_count, group_totals| -%>
  <% if group_name %>
    <% reset_cycle %>
    <tr class="group open">
      <td colspan="<%= @query.inline_columns.size + 2 %>">
        <span class="expander icon icon-expended" onclick="toggleRowGroup(this);">&nbsp;</span>
        <span class="name"><%= group_name %></span>
        <% if group_count %>
        <span class="badge badge-count count"><%= group_count %></span>
        <% end %>
        <span class="totals"><%= group_totals %></span>
        <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                             "toggleAllRowGroups(this)", :class => 'toggle-all') %>
      </td>
    </tr>
  <% end %>
  <tr id="time-entry-<%= entry.id %>" class="time-entry <%= cycle("odd", "even") %> hascontextmenu">
    <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", entry.id, false, :id => nil) %></td>
    <% @query.inline_columns.each do |column| %>
    <%= content_tag('td', column_content(column, entry), :class => column.css_classes) %>
    <% end %>
    <td class="buttons">
    <% if entry.editable_by?(User.current) -%>
          <%= link_to "PDF", show_time_entries_path(entry,:format=>'pdf'),
                :title => "PDF",
                :class => 'icon-only icon-save' %>
        <%= link_to l(:button_edit), edit_time_entry_path(entry),
                    :title => l(:button_edit),
                    :class => 'icon-only icon-edit' %>
        <%= link_to l(:button_delete), time_entry_path(entry),
                    :data => {:confirm => l(:text_are_you_sure)},
                    :method => :delete,
                    :title => l(:button_delete),
                    :class => 'icon-only icon-del' %>
    <% end -%>
        <%= link_to_context_menu %>
    </td>
  </tr>

  <% @query.block_columns.each do |column|
       if (text = column_content(column, entry)) && text.present? -%>
  <tr class="<%= current_cycle %>">
    <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
    <% if @query.block_columns.count > 1 %>
      <span><%= column.caption %></span>
    <% end %>
    <%= text %>
    </td>
  </tr>
  <% end -%>
  <% end -%>
<% end -%>
</tbody>
</table>
</div>
<% end -%>

<%= context_menu %>

app/views/timelog/index.html.erb
<div class="contextual">
<%= link_to l(:button_log_time),
            _new_time_entry_path(@project, @query.filtered_issue_id),
            :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project, :global => true) %>
<% if Redmine::VERSION::MAJOR == 4 && Redmine::VERSION::MINOR > 0 && Redmine::VERSION::TINY > 0%>
  <%= actions_dropdown do %>
    <% if User.current.allowed_to?(:import_time_entries, @project, :global => true) %>
      <%= link_to l(:button_import), new_time_entries_import_path(:project_id => @project), :class => 'icon icon-import' %>
    <% end %>
    <%= link_to_if_authorized l(:label_settings),
              {:controller => 'projects', :action => 'settings', :id => @project, :tab => 'activities'},
              :class => 'icon icon-settings' if User.current.allowed_to?(:manage_project_activities, @project) %>
  <% end %>
<% end %>
</div>

<h2><%= @query.new_record? ? l(:label_spent_time) : @query.name %></h2>

<%= form_tag(_time_entries_path(@project, nil), :method => :get, :id => 'query_form') do %>
<%= render :partial => 'date_range' %>
<% end %>

<% if @query.valid? %>
  <% if @entries.empty? %>
      <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
      <%= render_query_totals(@query) %>
      <%= render :partial => 'list', :locals => { :entries => @entries }%>
      <span class="pagination"><%= pagination_links_full @entry_pages, @entry_count %></span>

      <% other_formats_links do |f| %>
        <%= f.link_to_with_query_parameters 'Atom', :key => User.current.rss_key %>
        <%= f.link_to_with_query_parameters 'CSV', {}, :onclick => "showModal('csv-export-options', '330px'); return false;" %>
        <%= f.link_to_with_query_parameters 'PDF', {}, :onclick => "showModal('pdf-export-options', '330px'); return false;" %>
      <% end %>

      <div id="csv-export-options" style="display:none;">
        <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
        <%= form_tag(_time_entries_path(@project, nil, :format => 'csv'), :method => :get, :id => 'csv-export-form') do %>
          <%= query_as_hidden_field_tags @query %>
          <p>
            <label><%= radio_button_tag 'c[]', '', true %> <%= l(:description_selected_columns) %></label><br />
            <label><%= radio_button_tag 'c[]', 'all_inline' %> <%= l(:description_all_columns) %></label>
          </p>
          <% if @query.available_block_columns.any? %>
            <fieldset id="csv-export-block-columns">
              <legend>
                <%= toggle_checkboxes_link('#csv-export-block-columns input[type=checkbox]') %>
              </legend>
              <% @query.available_block_columns.each do |column| %>
                <label><%= check_box_tag 'c[]', column.name, @query.has_column?(:column), :id => nil %> <%= column.caption %></label>
              <% end %>
            </fieldset>
          <% end %>
          <%= export_csv_encoding_select_tag %>
          <p class="buttons">
            <%= submit_tag l(:button_export), :name => nil, :onclick => "hideModal(this);", :data => { :disable_with => false } %>
            <%= link_to_function l(:button_cancel), "hideModal(this);" %>
          </p>
        <% end %>
      </div>
      
      <div id="pdf-export-options" style="display:none;">
        <h3 class="title"><%= l(:label_export_options, :export_format => 'PDF') %></h3>
        <%= form_tag(_time_entries_path(@project, nil, :format => 'pdf'), :method => :get, :id => 'pdf-export-form') do %>
          <%= query_as_hidden_field_tags @query %>
          <p>
            <label><%= radio_button_tag 'c[]', '', true %> <%= l(:description_selected_columns) %></label><br />
            <label><%= radio_button_tag 'c[]', 'all_inline' %> <%= l(:description_all_columns) %></label>
          </p>
          <% if @query.available_block_columns.any? %>
            <fieldset id="pdf-export-block-columns">
              <legend>
                <%= toggle_checkboxes_link('#pdf-export-block-columns input[type=checkbox]') %>
              </legend>
              <% @query.available_block_columns.each do |column| %>
                <label><%= check_box_tag 'c[]', column.name, @query.has_column?(:column), :id => nil %> <%= column.caption %></label>
              <% end %>
            </fieldset>
          <% end %>
          
          <p class="buttons">
            <%= submit_tag l(:button_export), :name => nil, :onclick => "hideModal(this);", :data => { :disable_with => false } %>
            <%= link_to_function l(:button_cancel), "hideModal(this);" %>
          </p>
        <% end %>
      </div>
  <% end %>
<% end %>


<% content_for :sidebar do %>
  <%= render_sidebar_queries(TimeEntryQuery, @project) %>
<% end %>

<% html_title(@query.new_record? ? l(:label_spent_time) : @query.name, l(:label_details)) %>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, {:issue_id => @issue, :format => 'atom', :key => User.current.rss_key}, :title => l(:label_spent_time)) %>
<% end %>

app/views/timelog/show.pdf.erb
<%= raw timelog_to_pdf(@time_entry) %>